import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

/// Catalog copy for Fukaha's five locales. The package itself has no i18n.
const catalogTranslations = <String, Map<String, String>>{
  'en': {
    'app_title': 'Safaeh',
    'language': 'Language',
    'theme': 'Theme',
    'theme_light': 'Light',
    'theme_dark': 'Dark',
    'preview_phone': 'Phone layout',
    'sheet_placement_center':
        'Raise the sheet so the first content center aligns with the phone center',
    'sheet_placement_bottom': 'Use a compact bottom sheet',
    'sheet': 'Adaptive sheet',
    'sheet_sub': 'Phone sheet ↔ tablet dialog',
    'picker': 'Card picker',
    'picker_sub': 'Card rows with an icon and subtitle',
    'tile_picker': 'Tile picker',
    'tile_picker_sub': 'Header, leading icon, and a disabled row',
    'multi_picker': 'Multi picker',
    'multi_picker_sub': 'Search + confirm a list',
    'status_body': 'Status body',
    'status_body_sub': 'Empty / busy / action',
    'search_accounts': 'Search',
    'no_matches': 'No matches',
    'apply': 'Apply',
    'loading': 'Loading',
    'nothing_here': 'Nothing here yet',
    'try_again': 'Try again',
    'confirm': 'Confirm',
    'confirm_sub': 'Destructive phone cancel + confirm',
    'text_input': 'Text input',
    'text_input_sub': 'Trimmed result',
    'sheet_shell': 'Sheet shell',
    'sheet_shell_sub': 'Shared title, body, and action row',
    'sheet_morph': 'Sheet morph',
    'sheet_morph_sub': 'Phone 320 and tablet 420',
    'option_tiles': 'Option tiles',
    'option_tiles_sub': 'Selected / disabled / destructive',
    'dialog': 'Centered dialog',
    'dialog_sub': 'Centered panel',
    'sidenav': 'Sidenav rail',
    'sidenav_sub': 'Collapsed and expanded',
    'sidenav_drawer': 'Sidenav drawer',
    'sidenav_drawer_sub': 'Temporary drawer over a host',
    'floating_nav': 'Floating nav',
    'floating_nav_sub': 'Phone destination bar',
    'page_index': 'Page index',
    'page_index_sub': 'Rail, overlay, and scroll helper',
    'page_index_overlay': 'Page index overlay',
    'page_index_overlay_sub': 'Narrow floating pill',
    'content_band': 'Content band',
    'content_band_sub': 'Centered column + aside',
    'end_aside': 'End aside layout',
    'end_aside_sub': 'Manual band offset and width',
    'aligned_chrome': 'Aligned app bar + FAB',
    'aligned_chrome_sub': 'App bar and FAB on the band',
    'camera': 'Camera host',
    'camera_sub': 'Mock preview — no camera plugin',
    'qr_overlay': 'QR overlay',
    'qr_overlay_sub': 'Camera sheet + scan line',
    'qr_message': 'QR message',
    'qr_message_sub': 'Permission chrome in the camera sheet',
    'rename': 'Rename',
    'name': 'Name',
    'settle': 'How to settle',
    'minimal': 'Minimal',
    'minimal_sub': 'Fewest transfers',
    'pairs': 'Pairs',
    'pairs_sub': 'Per pair',
    'picker_footer': 'Host apps pass copy. No .tr() in the package.',
    'choose_account': 'Choose account',
    'header_hint': 'Custom header above the list',
    'cash': 'Cash',
    'card': 'Card',
    'offline': 'Offline',
    'delete_item': 'Delete item',
    'cannot_undo': 'This cannot be undone.',
    'delete': 'Delete',
    'cancel': 'Cancel',
    'close': 'Close',
    'tag_name': 'Tag name',
    'done': 'Done',
    'work': 'Work',
    'dismissed': 'Dismissed',
    'shell_body': 'Shared title, body, and action row.',
    'export_report': 'Export report',
    'shell_csv': 'CSV',
    'shell_pdf': 'PDF',
    'shell_picked_csv': 'Exporting as CSV',
    'shell_picked_pdf': 'Exporting as PDF',
    'save': 'Save',
    'selected': 'Selected',
    'selected_sub': 'Selected fill',
    'disabled': 'Disabled',
    'disabled_sub': 'Does not accept taps',
    'destructive': 'Destructive',
    'destructive_sub': 'Error color',
    'dialog_body': 'Centered dialog',
    'groups': 'Groups',
    'settings': 'Settings',
    'expand': 'Expand',
    'collapse': 'Collapse',
    'toggle_rail': 'Tap the menu to show destination labels.',
    'profile_name': 'Ada Lovelace',
    'profile_email': 'ada@example.com',
    'home': 'Home',
    'nav_page_copy': 'This is the selected destination.',
    'section_copy': 'A long page section the index can jump to.',
    'on_this_page': 'On this page',
    'alpha': 'Alpha',
    'beta': 'Beta',
    'gamma': 'Gamma',
    'aside': 'Aside',
    'band_copy':
        'SafaehContentBand centers a max-width column from incoming constraints. Aside is hidden on narrow screens.',
    'aside_copy': 'Manual SafaehEndAsideLayout offsets.',
    'aligned_title': 'Aligned title',
    'add': 'Add',
    'demo_camera': 'Demo camera',
    'scan_invite': 'Scan invite',
    'point_at_code': 'Point at a code',
    'need_camera': 'Need camera permission',
    'open_settings': 'Open settings',
  },
  'ar': {
    'app_title': 'صفائح',
    'language': 'اللغة',
    'theme': 'المظهر',
    'theme_light': 'فاتح',
    'theme_dark': 'داكن',
    'preview_phone': 'تخطيط الهاتف',
    'sheet_placement_center': 'رفع الورقة حتى يحاذي مركز أول محتوى مركز الهاتف',
    'sheet_placement_bottom': 'ورقة سفلية مدمجة',
    'sheet': 'ورقة متكيفة',
    'sheet_sub': 'ورقة هاتف ↔ حوار لوحي',
    'picker': 'منتقي البطاقات',
    'picker_sub': 'بطاقات مع أيقونة ونص فرعي',
    'tile_picker': 'منتقي الصفوف',
    'tile_picker_sub': 'ترويسة وأيقونة وصف معطل',
    'multi_picker': 'منتقي متعدد',
    'multi_picker_sub': 'بحث وتأكيد قائمة',
    'status_body': 'حالة فارغة',
    'status_body_sub': 'فارغ / مشغول / إجراء',
    'search_accounts': 'بحث',
    'no_matches': 'لا نتائج',
    'apply': 'تطبيق',
    'loading': 'جارٍ التحميل',
    'nothing_here': 'لا شيء هنا بعد',
    'try_again': 'حاول مرة أخرى',
    'confirm': 'تأكيد',
    'confirm_sub': 'حذف مع إلغاء على الهاتف',
    'text_input': 'إدخال نص',
    'text_input_sub': 'نتيجة بعد القص',
    'sheet_shell': 'هيكل الورقة',
    'sheet_shell_sub': 'عنوان ونص وصف أفعال مشتركة',
    'sheet_morph': 'تحول الورقة',
    'sheet_morph_sub': 'هاتف 320 ولوحي 420',
    'option_tiles': 'صفوف الخيارات',
    'option_tiles_sub': 'محدد / معطّل / خطر',
    'dialog': 'حوار مركزي',
    'dialog_sub': 'لوحة في الوسط',
    'sidenav': 'سكة جانبية',
    'sidenav_sub': 'مطوية وموسّعة',
    'sidenav_drawer': 'درج جانبي',
    'sidenav_drawer_sub': 'درج مؤقت فوق المضيف',
    'floating_nav': 'شريط عائم',
    'floating_nav_sub': 'شريط وجهات للهاتف',
    'page_index': 'فهرس الصفحة',
    'page_index_sub': 'سكة، طبقة عائمة، وتمرير للأقسام',
    'page_index_overlay': 'فهرس عائم',
    'page_index_overlay_sub': 'حبة عائمة للشاشات الضيقة',
    'content_band': 'شريط المحتوى',
    'content_band_sub': 'عمود مركزي + جانب',
    'end_aside': 'تخطيط الجانب',
    'end_aside_sub': 'إزاحات يدوية للعمود',
    'aligned_chrome': 'شريط ومحاذاة الزر',
    'aligned_chrome_sub': 'شريط تطبيق وزر عائم على العمود',
    'camera': 'مضيف الكاميرا',
    'camera_sub': 'معاينة وهمية — بلا إضافة كاميرا',
    'qr_overlay': 'تراكب QR',
    'qr_overlay_sub': 'ورقة كاميرا + خط مسح',
    'qr_message': 'رسالة QR',
    'qr_message_sub': 'صلاحية داخل ورقة الكاميرا',
    'rename': 'إعادة التسمية',
    'name': 'الاسم',
    'settle': 'طريقة التسوية',
    'minimal': 'أقصر مسار',
    'minimal_sub': 'أقل تحويلات',
    'pairs': 'أزواج',
    'pairs_sub': 'لكل زوج',
    'picker_footer': 'التطبيق يمرّر النصوص. لا .tr() في الحزمة.',
    'choose_account': 'اختر حساباً',
    'header_hint': 'ترويسة مخصصة فوق القائمة',
    'cash': 'نقد',
    'card': 'بطاقة',
    'offline': 'غير متصل',
    'delete_item': 'حذف العنصر',
    'cannot_undo': 'لا يمكن التراجع.',
    'delete': 'حذف',
    'cancel': 'إلغاء',
    'close': 'إغلاق',
    'tag_name': 'اسم الوسم',
    'done': 'تم',
    'work': 'عمل',
    'dismissed': 'أُغلق',
    'shell_body': 'عنوان ومحتوى وصف أزرار مشتركة.',
    'export_report': 'تصدير التقرير',
    'shell_csv': 'CSV',
    'shell_pdf': 'PDF',
    'shell_picked_csv': 'التصدير كـ CSV',
    'shell_picked_pdf': 'التصدير كـ PDF',
    'save': 'حفظ',
    'selected': 'محدد',
    'selected_sub': 'تعبئة التحديد',
    'disabled': 'معطّل',
    'disabled_sub': 'لا يقبل النقر',
    'destructive': 'خطر',
    'destructive_sub': 'لون الخطأ',
    'dialog_body': 'حوار في الوسط',
    'groups': 'المجموعات',
    'settings': 'الإعدادات',
    'expand': 'توسيع',
    'collapse': 'طي',
    'toggle_rail': 'اضغط القائمة لإظهار تسميات الوجهات.',
    'profile_name': 'Ada Lovelace',
    'profile_email': 'ada@example.com',
    'home': 'الرئيسية',
    'nav_page_copy': 'هذه هي الوجهة المحددة.',
    'section_copy': 'قسم طويل يمكن للفهرس الانتقال إليه.',
    'on_this_page': 'في هذه الصفحة',
    'alpha': 'ألفا',
    'beta': 'بيتا',
    'gamma': 'غاما',
    'aside': 'جانب',
    'band_copy':
        'SafaehContentBand يوسّط عموداً بحد أقصى من القيود الواردة. الجانب يُخفى على الشاشات الضيقة.',
    'aside_copy': 'إزاحات SafaehEndAsideLayout اليدوية.',
    'aligned_title': 'عنوان محاذى',
    'add': 'إضافة',
    'demo_camera': 'كاميرا تجريبية',
    'scan_invite': 'امسح الدعوة',
    'point_at_code': 'وجّه نحو الرمز',
    'need_camera': 'يلزم إذن الكاميرا',
    'open_settings': 'افتح الإعدادات',
  },
  'ja': {
    'app_title': 'Safaeh',
    'language': '言語',
    'theme': 'テーマ',
    'theme_light': 'ライト',
    'theme_dark': 'ダーク',
    'preview_phone': 'スマホレイアウト',
    'sheet_placement_center': '最初の内容の中央が端末の中央に揃うようシートを上げる',
    'sheet_placement_bottom': 'コンパクトな下シート',
    'sheet': 'アダプティブシート',
    'sheet_sub': '電話シート ↔ タブレットダイアログ',
    'picker': 'カードピッカー',
    'picker_sub': 'アイコンと字幕のカード',
    'tile_picker': 'タイルピッカー',
    'tile_picker_sub': 'ヘッダー、先頭アイコン、無効行',
    'multi_picker': '複数選択',
    'multi_picker_sub': '検索してリストを確定',
    'status_body': 'ステータス',
    'status_body_sub': '空 / 読み込み / 操作',
    'search_accounts': '検索',
    'no_matches': '一致なし',
    'apply': '適用',
    'loading': '読み込み中',
    'nothing_here': 'まだありません',
    'try_again': '再試行',
    'confirm': '確認',
    'confirm_sub': '破壊的な電話キャンセル + 確認',
    'text_input': 'テキスト入力',
    'text_input_sub': 'トリムした値',
    'sheet_shell': 'シートシェル',
    'sheet_shell_sub': '共有のタイトル、本文、操作',
    'sheet_morph': 'シートの変形',
    'sheet_morph_sub': '電話 320 とタブレット 420',
    'option_tiles': 'オプションタイル',
    'option_tiles_sub': '選択 / 無効 / 破壊的',
    'dialog': '中央ダイアログ',
    'dialog_sub': '中央のパネル',
    'sidenav': 'サイドナビゲーション',
    'sidenav_sub': '折りたたみと展開',
    'sidenav_drawer': 'サイドナビゲーションドロワー',
    'sidenav_drawer_sub': 'ホストの上の一時ドロワー',
    'floating_nav': 'フローティングナビ',
    'floating_nav_sub': '電話の行き先バー',
    'page_index': 'ページ索引',
    'page_index_sub': 'レール・オーバーレイ・スクロール',
    'page_index_overlay': 'ページ索引オーバーレイ',
    'page_index_overlay_sub': '狭い画面のフローティングピル',
    'content_band': 'コンテンツバンド',
    'content_band_sub': '中央カラム + サイド',
    'end_aside': 'エンドサイドレイアウト',
    'end_aside_sub': '手動の帯オフセットと幅',
    'aligned_chrome': '整列したバーと FAB',
    'aligned_chrome_sub': '帯上のアプリバーとボタン',
    'camera': 'カメラホスト',
    'camera_sub': 'モックプレビュー — カメラプラグインなし',
    'qr_overlay': 'QR オーバーレイ',
    'qr_overlay_sub': 'カメラシート + スキャンライン',
    'qr_message': 'QR メッセージ',
    'qr_message_sub': 'カメラシート内の権限クロム',
    'rename': '名前を変更',
    'name': '名前',
    'settle': '精算方法',
    'minimal': '最小',
    'minimal_sub': '最少の送金',
    'pairs': 'ペア',
    'pairs_sub': 'ペアごと',
    'picker_footer': 'ホストアプリが文言を渡します。パッケージに .tr() はありません。',
    'choose_account': '口座を選択',
    'header_hint': 'リスト上のカスタムヘッダー',
    'cash': '現金',
    'card': 'カード',
    'offline': 'オフライン',
    'delete_item': '項目を削除',
    'cannot_undo': '元に戻せません。',
    'delete': '削除',
    'cancel': 'キャンセル',
    'close': '閉じる',
    'tag_name': 'タグ名',
    'done': '完了',
    'work': '仕事',
    'dismissed': '閉じました',
    'shell_body': '共有のタイトル、本文、アクション行。',
    'export_report': 'レポートを書き出す',
    'shell_csv': 'CSV',
    'shell_pdf': 'PDF',
    'shell_picked_csv': 'CSV で書き出し',
    'shell_picked_pdf': 'PDF で書き出し',
    'save': '保存',
    'selected': '選択済み',
    'selected_sub': '選択時の塗り',
    'disabled': '無効',
    'disabled_sub': 'タップを受け付けません',
    'destructive': '破壊的',
    'destructive_sub': 'エラー色',
    'dialog_body': '中央のダイアログ',
    'groups': 'グループ',
    'settings': '設定',
    'expand': '展開',
    'collapse': '折りたたむ',
    'toggle_rail': 'メニューをタップしてラベルを表示します。',
    'profile_name': 'Ada Lovelace',
    'profile_email': 'ada@example.com',
    'home': 'ホーム',
    'nav_page_copy': '選択中の行き先です。',
    'section_copy': 'インデックスがジャンプできる長いセクションです。',
    'on_this_page': 'このページ',
    'alpha': 'アルファ',
    'beta': 'ベータ',
    'gamma': 'ガンマ',
    'aside': 'サイド',
    'band_copy': 'SafaehContentBand は入ってきた制約から最大幅のカラムを中央に置きます。狭い画面ではサイドは隠れます。',
    'aside_copy': '手動の SafaehEndAsideLayout オフセット。',
    'aligned_title': '整列したタイトル',
    'add': '追加',
    'demo_camera': 'デモカメラ',
    'scan_invite': '招待をスキャン',
    'point_at_code': 'コードに向ける',
    'need_camera': 'カメラの許可が必要です',
    'open_settings': '設定を開く',
  },
  'zh': {
    'app_title': 'Safaeh',
    'language': '语言',
    'theme': '主题',
    'theme_light': '浅色',
    'theme_dark': '深色',
    'preview_phone': '手机布局',
    'sheet_placement_center': '升高弹层使首块内容中心对齐手机中心',
    'sheet_placement_bottom': '使用紧凑底部弹层',
    'sheet': '自适应表单',
    'sheet_sub': '手机底栏 ↔ 平板对话框',
    'picker': '卡片选择器',
    'picker_sub': '带图标和副标题的卡片',
    'tile_picker': '列表选择器',
    'tile_picker_sub': '标题、前置图标、禁用行',
    'multi_picker': '多选列表',
    'multi_picker_sub': '搜索并确认列表',
    'status_body': '状态页',
    'status_body_sub': '空 / 忙碌 / 操作',
    'search_accounts': '搜索',
    'no_matches': '无匹配',
    'apply': '应用',
    'loading': '加载中',
    'nothing_here': '暂无内容',
    'try_again': '重试',
    'confirm': '确认',
    'confirm_sub': '危险操作的取消 + 确认',
    'text_input': '文本输入',
    'text_input_sub': '修剪后的结果',
    'sheet_shell': '表单外壳',
    'sheet_shell_sub': '共用的标题、正文和操作',
    'sheet_morph': '表单形态',
    'sheet_morph_sub': '手机 320 与平板 420',
    'option_tiles': '选项行',
    'option_tiles_sub': '已选 / 禁用 / 危险',
    'dialog': '居中对话框',
    'dialog_sub': '居中面板',
    'sidenav': '侧栏',
    'sidenav_sub': '折叠与展开',
    'sidenav_drawer': '侧栏抽屉',
    'sidenav_drawer_sub': '覆盖宿主的临时抽屉',
    'floating_nav': '浮动导航',
    'floating_nav_sub': '手机底部导航',
    'page_index': '页面索引',
    'page_index_sub': '侧栏、浮层与滚动辅助',
    'page_index_overlay': '页面索引浮层',
    'page_index_overlay_sub': '窄屏浮动胶囊',
    'content_band': '内容带',
    'content_band_sub': '居中列 + 侧栏',
    'end_aside': '末端侧栏布局',
    'end_aside_sub': '手动的带偏移和宽度',
    'aligned_chrome': '对齐的栏与 FAB',
    'aligned_chrome_sub': '内容带上的应用栏和按钮',
    'camera': '相机宿主',
    'camera_sub': '模拟预览 — 无相机插件',
    'qr_overlay': 'QR 叠加',
    'qr_overlay_sub': '相机表单 + 扫描线',
    'qr_message': 'QR 消息',
    'qr_message_sub': '相机表单中的权限铬',
    'rename': '重命名',
    'name': '名称',
    'settle': '如何结算',
    'minimal': '最少',
    'minimal_sub': '最少转账',
    'pairs': '成对',
    'pairs_sub': '每对',
    'picker_footer': '宿主应用传入文案。包内没有 .tr()。',
    'choose_account': '选择账户',
    'header_hint': '列表上方的自定义标题',
    'cash': '现金',
    'card': '卡片',
    'offline': '离线',
    'delete_item': '删除项目',
    'cannot_undo': '此操作无法撤销。',
    'delete': '删除',
    'cancel': '取消',
    'close': '关闭',
    'tag_name': '标签名',
    'done': '完成',
    'work': '工作',
    'dismissed': '已关闭',
    'shell_body': '共享的标题、正文和操作行。',
    'export_report': '导出报告',
    'shell_csv': 'CSV',
    'shell_pdf': 'PDF',
    'shell_picked_csv': '正在导出为 CSV',
    'shell_picked_pdf': '正在导出为 PDF',
    'save': '保存',
    'selected': '已选',
    'selected_sub': '选中填充',
    'disabled': '禁用',
    'disabled_sub': '不接受点击',
    'destructive': '危险',
    'destructive_sub': '错误色',
    'dialog_body': '居中对话框',
    'groups': '群组',
    'settings': '设置',
    'expand': '展开',
    'collapse': '折叠',
    'toggle_rail': '点按菜单以显示目标标签。',
    'profile_name': 'Ada Lovelace',
    'profile_email': 'ada@example.com',
    'home': '首页',
    'nav_page_copy': '这是当前选中的目的地。',
    'section_copy': '索引可以跳转到的长页面章节。',
    'on_this_page': '本页',
    'alpha': '阿尔法',
    'beta': '贝塔',
    'gamma': '伽马',
    'aside': '侧栏',
    'band_copy': 'SafaehContentBand 根据传入约束将最大宽度列居中。窄屏时隐藏侧栏。',
    'aside_copy': '手动的 SafaehEndAsideLayout 偏移。',
    'aligned_title': '对齐标题',
    'add': '添加',
    'demo_camera': '演示相机',
    'scan_invite': '扫描邀请',
    'point_at_code': '对准代码',
    'need_camera': '需要相机权限',
    'open_settings': '打开设置',
  },
  'es': {
    'app_title': 'Safaeh',
    'language': 'Idioma',
    'theme': 'Tema',
    'theme_light': 'Claro',
    'theme_dark': 'Oscuro',
    'preview_phone': 'Diseño de teléfono',
    'sheet_placement_center':
        'Elevar la hoja para alinear el centro del primer contenido con el del teléfono',
    'sheet_placement_bottom': 'Usar una hoja inferior compacta',
    'sheet': 'Hoja adaptativa',
    'sheet_sub': 'Hoja de teléfono ↔ diálogo de tablet',
    'picker': 'Selector de tarjetas',
    'picker_sub': 'Tarjetas con icono y subtítulo',
    'tile_picker': 'Selector de filas',
    'tile_picker_sub': 'Cabecera, icono inicial y fila desactivada',
    'multi_picker': 'Selector múltiple',
    'multi_picker_sub': 'Buscar y confirmar una lista',
    'status_body': 'Estado vacío',
    'status_body_sub': 'Vacío / ocupado / acción',
    'search_accounts': 'Buscar',
    'no_matches': 'Sin coincidencias',
    'apply': 'Aplicar',
    'loading': 'Cargando',
    'nothing_here': 'Aún no hay nada',
    'try_again': 'Reintentar',
    'confirm': 'Confirmar',
    'confirm_sub': 'Cancelar + confirmar destructivo',
    'text_input': 'Entrada de texto',
    'text_input_sub': 'Resultado recortado',
    'sheet_shell': 'Cáscara de hoja',
    'sheet_shell_sub': 'Título, cuerpo y acciones compartidos',
    'sheet_morph': 'Cambio de hoja',
    'sheet_morph_sub': 'Teléfono 320 y tablet 420',
    'option_tiles': 'Filas de opciones',
    'option_tiles_sub': 'Seleccionado / desactivado / destructivo',
    'dialog': 'Diálogo centrado',
    'dialog_sub': 'Panel centrado',
    'sidenav': 'Navegación lateral',
    'sidenav_sub': 'Contraída y expandida',
    'sidenav_drawer': 'Cajón lateral',
    'sidenav_drawer_sub': 'Cajón temporal sobre el anfitrión',
    'floating_nav': 'Navegación flotante',
    'floating_nav_sub': 'Barra de destinos en el teléfono',
    'page_index': 'Índice de página',
    'page_index_sub': 'Rail, overlay y desplazamiento',
    'page_index_overlay': 'Índice flotante',
    'page_index_overlay_sub': 'Píldora flotante en pantallas estrechas',
    'content_band': 'Banda de contenido',
    'content_band_sub': 'Columna centrada + lateral',
    'end_aside': 'Diseño lateral',
    'end_aside_sub': 'Desplazamiento y ancho de banda manuales',
    'aligned_chrome': 'Barra y FAB alineados',
    'aligned_chrome_sub': 'Barra y botón flotante sobre la banda',
    'camera': 'Anfitrión de cámara',
    'camera_sub': 'Vista previa simulada — sin plugin de cámara',
    'qr_overlay': 'Superposición QR',
    'qr_overlay_sub': 'Hoja de cámara + línea de escaneo',
    'qr_message': 'Mensaje QR',
    'qr_message_sub': 'Permiso en la hoja de cámara',
    'rename': 'Renombrar',
    'name': 'Nombre',
    'settle': 'Cómo saldar',
    'minimal': 'Mínimo',
    'minimal_sub': 'Menos transferencias',
    'pairs': 'Pares',
    'pairs_sub': 'Por par',
    'picker_footer':
        'La app anfitriona pasa el texto. No hay .tr() en el paquete.',
    'choose_account': 'Elegir cuenta',
    'header_hint': 'Cabecera personalizada sobre la lista',
    'cash': 'Efectivo',
    'card': 'Tarjeta',
    'offline': 'Sin conexión',
    'delete_item': 'Eliminar elemento',
    'cannot_undo': 'Esto no se puede deshacer.',
    'delete': 'Eliminar',
    'cancel': 'Cancelar',
    'close': 'Cerrar',
    'tag_name': 'Nombre de etiqueta',
    'done': 'Hecho',
    'work': 'Trabajo',
    'dismissed': 'Cerrado',
    'shell_body': 'Título, cuerpo y fila de acciones compartidos.',
    'export_report': 'Exportar informe',
    'shell_csv': 'CSV',
    'shell_pdf': 'PDF',
    'shell_picked_csv': 'Exportando como CSV',
    'shell_picked_pdf': 'Exportando como PDF',
    'save': 'Guardar',
    'selected': 'Seleccionado',
    'selected_sub': 'Relleno de selección',
    'disabled': 'Desactivado',
    'disabled_sub': 'No acepta toques',
    'destructive': 'Destructivo',
    'destructive_sub': 'Color de error',
    'dialog_body': 'Diálogo centrado',
    'groups': 'Grupos',
    'settings': 'Ajustes',
    'expand': 'Expandir',
    'collapse': 'Contraer',
    'toggle_rail': 'Toca el menú para mostrar las etiquetas.',
    'profile_name': 'Ada Lovelace',
    'profile_email': 'ada@example.com',
    'home': 'Inicio',
    'nav_page_copy': 'Este es el destino seleccionado.',
    'section_copy': 'Una sección larga a la que el índice puede saltar.',
    'on_this_page': 'En esta página',
    'alpha': 'Alfa',
    'beta': 'Beta',
    'gamma': 'Gamma',
    'aside': 'Lateral',
    'band_copy':
        'SafaehContentBand centra una columna de ancho máximo desde las restricciones entrantes. El lateral se oculta en pantallas estrechas.',
    'aside_copy': 'Desplazamientos manuales de SafaehEndAsideLayout.',
    'aligned_title': 'Título alineado',
    'add': 'Añadir',
    'demo_camera': 'Cámara de demostración',
    'scan_invite': 'Escanear invitación',
    'point_at_code': 'Apunta a un código',
    'need_camera': 'Se necesita permiso de cámara',
    'open_settings': 'Abrir ajustes',
  },
};

/// Fukaha language menu order: AR, EN, JA, ZH, ES. Arabic is the only RTL.
class CatalogLocale {
  const CatalogLocale({
    required this.code,
    required this.locale,
    required this.label,
    required this.flag,
    required this.shortCode,
  });

  final String code;
  final Locale locale;
  final String label;
  final String flag;
  final String shortCode;

  bool get isRtl => code == 'ar';
}

const catalogLocales = <CatalogLocale>[
  CatalogLocale(
    code: 'ar',
    locale: Locale('ar'),
    label: 'العربية',
    flag: '🇸🇦',
    shortCode: 'AR',
  ),
  CatalogLocale(
    code: 'en',
    locale: Locale('en'),
    label: 'English',
    flag: '🇬🇧',
    shortCode: 'EN',
  ),
  CatalogLocale(
    code: 'ja',
    locale: Locale('ja'),
    label: '日本語',
    flag: '🇯🇵',
    shortCode: 'JA',
  ),
  CatalogLocale(
    code: 'zh',
    locale: Locale.fromSubtags(languageCode: 'zh', countryCode: 'CN'),
    label: '简体中文',
    flag: '🇨🇳',
    shortCode: 'ZH',
  ),
  CatalogLocale(
    code: 'es',
    locale: Locale('es'),
    label: 'Español',
    flag: '🇪🇸',
    shortCode: 'ES',
  ),
];

/// Catalog has no camera plugin. Web and desktop have no lens; phone builds
/// of this example also get the mock so chrome stays demoable.
bool catalogNeedsMockCamera() {
  if (kIsWeb) return true;
  return switch (defaultTargetPlatform) {
    TargetPlatform.macOS ||
    TargetPlatform.windows ||
    TargetPlatform.linux ||
    TargetPlatform.fuchsia ||
    TargetPlatform.android ||
    TargetPlatform.iOS => true,
  };
}

Locale catalogFlutterLocale(String code) {
  for (final item in catalogLocales) {
    if (item.code == code) return item.locale;
  }
  return const Locale('en');
}

/// Keep emails and similar tokens LTR inside RTL chrome.
Widget catalogIsolateLabel(String data, TextStyle? style) {
  final text = Text(
    data,
    style: style,
    maxLines: 1,
    overflow: TextOverflow.ellipsis,
  );
  if (data.contains('@')) {
    return Directionality(
      textDirection: TextDirection.ltr,
      child: text,
    );
  }
  return text;
}

class CatalogItem {
  const CatalogItem({
    required this.id,
    required this.titleKey,
    this.subtitleKey,
  });

  final String id;
  final String titleKey;
  final String? subtitleKey;
}

const catalogItems = <CatalogItem>[
  CatalogItem(id: 'sheet', titleKey: 'sheet', subtitleKey: 'sheet_sub'),
  CatalogItem(id: 'picker', titleKey: 'picker', subtitleKey: 'picker_sub'),
  CatalogItem(
    id: 'tile_picker',
    titleKey: 'tile_picker',
    subtitleKey: 'tile_picker_sub',
  ),
  CatalogItem(
    id: 'multi_picker',
    titleKey: 'multi_picker',
    subtitleKey: 'multi_picker_sub',
  ),
  CatalogItem(id: 'confirm', titleKey: 'confirm', subtitleKey: 'confirm_sub'),
  CatalogItem(
    id: 'text_input',
    titleKey: 'text_input',
    subtitleKey: 'text_input_sub',
  ),
  CatalogItem(
    id: 'sheet_shell',
    titleKey: 'sheet_shell',
    subtitleKey: 'sheet_shell_sub',
  ),
  CatalogItem(
    id: 'sheet_morph',
    titleKey: 'sheet_morph',
    subtitleKey: 'sheet_morph_sub',
  ),
  CatalogItem(
    id: 'option_tiles',
    titleKey: 'option_tiles',
    subtitleKey: 'option_tiles_sub',
  ),
  CatalogItem(id: 'dialog', titleKey: 'dialog', subtitleKey: 'dialog_sub'),
  CatalogItem(id: 'sidenav', titleKey: 'sidenav', subtitleKey: 'sidenav_sub'),
  CatalogItem(
    id: 'sidenav_drawer',
    titleKey: 'sidenav_drawer',
    subtitleKey: 'sidenav_drawer_sub',
  ),
  CatalogItem(
    id: 'floating_nav',
    titleKey: 'floating_nav',
    subtitleKey: 'floating_nav_sub',
  ),
  CatalogItem(
    id: 'page_index',
    titleKey: 'page_index',
    subtitleKey: 'page_index_sub',
  ),
  CatalogItem(
    id: 'page_index_overlay',
    titleKey: 'page_index_overlay',
    subtitleKey: 'page_index_overlay_sub',
  ),
  CatalogItem(
    id: 'content_band',
    titleKey: 'content_band',
    subtitleKey: 'content_band_sub',
  ),
  CatalogItem(
    id: 'end_aside',
    titleKey: 'end_aside',
    subtitleKey: 'end_aside_sub',
  ),
  CatalogItem(
    id: 'aligned_chrome',
    titleKey: 'aligned_chrome',
    subtitleKey: 'aligned_chrome_sub',
  ),
  CatalogItem(id: 'camera', titleKey: 'camera', subtitleKey: 'camera_sub'),
  CatalogItem(
    id: 'qr_overlay',
    titleKey: 'qr_overlay',
    subtitleKey: 'qr_overlay_sub',
  ),
  CatalogItem(
    id: 'qr_message',
    titleKey: 'qr_message',
    subtitleKey: 'qr_message_sub',
  ),
  CatalogItem(
    id: 'status_body',
    titleKey: 'status_body',
    subtitleKey: 'status_body_sub',
  ),
];

/// Keys that stay the same in every locale (names, brands, file types).
const catalogSharedLiterals = {
  'app_title',
  'profile_name',
  'profile_email',
  'shell_csv',
  'shell_pdf',
  'beta',
  'gamma',
};

String translateCatalog(String key, String locale) {
  final table = catalogTranslations[locale];
  assert(
    table != null && table.containsKey(key),
    'Missing catalog key "$key" for locale "$locale"',
  );
  return table?[key] ?? catalogTranslations['en']?[key] ?? key;
}

/// Lays out catalog copy so CJK / Arabic glyphs exist before the page reveals.
Future<void> warmupCatalogLocale(String locale, {TextStyle? style}) async {
  final texts = catalogTranslations[locale];
  if (texts == null || texts.isEmpty) return;
  final painter = TextPainter(
    textDirection: locale == 'ar' ? TextDirection.rtl : TextDirection.ltr,
  );
  final resolved = style ?? const TextStyle(fontSize: 16, height: 1.3);
  for (final value in texts.values) {
    if (value.isEmpty) continue;
    painter.text = TextSpan(text: value, style: resolved);
    painter.layout(maxWidth: 480);
  }
  painter.dispose();
}
