/// Bilingual catalog copy. The package itself has no i18n.
const catalogTranslations = <String, Map<String, String>>{
  'en': {
    'app_title': 'Safaeh',
    'language': 'Language',
    'theme': 'Theme',
    'theme_light': 'Light',
    'theme_dark': 'Dark',
    'sheet': 'Adaptive sheet',
    'sheet_sub': 'Phone sheet ↔ tablet dialog',
    'picker': 'Card picker',
    'picker_sub': 'showSafaehPicker',
    'tile_picker': 'Tile picker',
    'tile_picker_sub': 'Header, leading, disabled row',
    'confirm': 'Confirm',
    'confirm_sub': 'Destructive phone cancel + confirm',
    'text_input': 'Text input',
    'text_input_sub': 'Trimmed result',
    'sheet_shell': 'Sheet shell',
    'sheet_shell_sub': 'buildSafaehSheetShell',
    'sheet_morph': 'Sheet morph',
    'sheet_morph_sub': 'Phone 400 and tablet 900',
    'option_tiles': 'Option tiles',
    'option_tiles_sub': 'Selected / disabled / destructive',
    'dialog': 'Centered dialog',
    'dialog_sub': 'showSafaehDialog',
    'sidenav': 'Sidenav rail',
    'sidenav_sub': 'Collapsed and expanded',
    'sidenav_drawer': 'Sidenav drawer',
    'sidenav_drawer_sub': 'asDrawer: true',
    'floating_nav': 'Floating nav',
    'floating_nav_sub': 'SafaehFloatingNavBar',
    'page_index': 'Page index',
    'page_index_sub': 'Side rail + scroll helper',
    'page_index_overlay': 'Page index overlay',
    'page_index_overlay_sub': 'Narrow floating pill',
    'content_band': 'Content band',
    'content_band_sub': 'Centered column + aside',
    'end_aside': 'End aside layout',
    'end_aside_sub': 'Manual leftOffset / bandWidth',
    'aligned_chrome': 'Aligned app bar + FAB',
    'aligned_chrome_sub': 'safaehBandMetrics',
    'camera': 'Camera host',
    'camera_sub': 'Mock child — no mobile_scanner',
    'qr_overlay': 'QR overlay',
    'qr_overlay_sub': 'AlwaysStoppedAnimation scan line',
    'qr_message': 'QR message',
    'qr_message_sub': 'Permission / unavailable chrome',
    'rename': 'Rename',
    'name': 'Name',
    'settle': 'How to settle',
    'minimal': 'Minimal',
    'minimal_sub': 'Fewest transfers',
    'pairs': 'Pairs',
    'pairs_sub': 'Per pair',
    'picker_footer': 'Host apps pass copy. No .tr() in the package.',
    'choose_account': 'Choose account',
    'header_hint': 'Custom header above the list',
    'cash': 'Cash',
    'card': 'Card',
    'offline': 'Offline',
    'delete_item': 'Delete item',
    'cannot_undo': 'This cannot be undone.',
    'delete': 'Delete',
    'cancel': 'Cancel',
    'tag_name': 'Tag name',
    'done': 'Done',
    'work': 'Work',
    'dismissed': 'Dismissed',
    'shell_body': 'Shared title, body, and action row.',
    'save': 'Save',
    'selected': 'Selected',
    'selected_sub': 'primaryContainer fill',
    'disabled': 'Disabled',
    'disabled_sub': 'Does not accept taps',
    'destructive': 'Destructive',
    'destructive_sub': 'colorScheme.error',
    'dialog_body': 'showSafaehDialog',
    'groups': 'Groups',
    'settings': 'Settings',
    'expand': 'Expand',
    'collapse': 'Collapse',
    'toggle_rail': 'Toggle the rail chevron',
    'home': 'Home',
    'selected_index': 'Selected',
    'on_this_page': 'On this page',
    'alpha': 'Alpha',
    'beta': 'Beta',
    'gamma': 'Gamma',
    'aside': 'Aside',
    'band_copy':
        'SafaehContentBand centers a max-width column from incoming constraints. Aside is hidden on narrow screens.',
    'aside_copy': 'Manual SafaehEndAsideLayout offsets.',
    'aligned_title': 'Aligned title',
    'add': 'Add',
    'mock_preview': 'Mock preview',
    'scan_invite': 'Scan invite',
    'point_at_code': 'Point at a code',
    'need_camera': 'Need camera permission',
    'open_settings': 'Open settings',
  },
  'ar': {
    'app_title': 'صفائح',
    'language': 'اللغة',
    'theme': 'المظهر',
    'theme_light': 'فاتح',
    'theme_dark': 'داكن',
    'sheet': 'ورقة متكيفة',
    'sheet_sub': 'ورقة هاتف ↔ حوار لوحي',
    'picker': 'منتقي البطاقات',
    'picker_sub': 'showSafaehPicker',
    'tile_picker': 'منتقي الصفوف',
    'tile_picker_sub': 'ترويسة وleading وصف معطل',
    'confirm': 'تأكيد',
    'confirm_sub': 'حذف مع إلغاء على الهاتف',
    'text_input': 'إدخال نص',
    'text_input_sub': 'نتيجة بعد القص',
    'sheet_shell': 'هيكل الورقة',
    'sheet_shell_sub': 'buildSafaehSheetShell',
    'sheet_morph': 'تحول الورقة',
    'sheet_morph_sub': 'هاتف 400 ولوحي 900',
    'option_tiles': 'صفوف الخيارات',
    'option_tiles_sub': 'محدد / معطّل / خطر',
    'dialog': 'حوار مركزي',
    'dialog_sub': 'showSafaehDialog',
    'sidenav': 'سكة جانبية',
    'sidenav_sub': 'مطوية وموسّعة',
    'sidenav_drawer': 'درج جانبي',
    'sidenav_drawer_sub': 'asDrawer: true',
    'floating_nav': 'شريط عائم',
    'floating_nav_sub': 'SafaehFloatingNavBar',
    'page_index': 'فهرس الصفحة',
    'page_index_sub': 'سكة + تمرير للأقسام',
    'page_index_overlay': 'فهرس عائم',
    'page_index_overlay_sub': 'حبة عائمة للشاشات الضيقة',
    'content_band': 'شريط المحتوى',
    'content_band_sub': 'عمود مركزي + جانب',
    'end_aside': 'تخطيط الجانب',
    'end_aside_sub': 'إزاحات يدوية',
    'aligned_chrome': 'شريط ومحاذاة الزر',
    'aligned_chrome_sub': 'safaehBandMetrics',
    'camera': 'مضيف الكاميرا',
    'camera_sub': 'طفل وهمي — بلا mobile_scanner',
    'qr_overlay': 'تراكب QR',
    'qr_overlay_sub': 'خط مسح ثابت',
    'qr_message': 'رسالة QR',
    'qr_message_sub': 'صلاحية / كاميرا غير متاحة',
    'rename': 'إعادة التسمية',
    'name': 'الاسم',
    'settle': 'طريقة التسوية',
    'minimal': 'أقصر مسار',
    'minimal_sub': 'أقل تحويلات',
    'pairs': 'أزواج',
    'pairs_sub': 'لكل زوج',
    'picker_footer': 'التطبيق يمرّر النصوص. لا .tr() في الحزمة.',
    'choose_account': 'اختر حساباً',
    'header_hint': 'ترويسة مخصصة فوق القائمة',
    'cash': 'نقد',
    'card': 'بطاقة',
    'offline': 'غير متصل',
    'delete_item': 'حذف العنصر',
    'cannot_undo': 'لا يمكن التراجع.',
    'delete': 'حذف',
    'cancel': 'إلغاء',
    'tag_name': 'اسم الوسم',
    'done': 'تم',
    'work': 'عمل',
    'dismissed': 'أُغلق',
    'shell_body': 'عنوان ومحتوى وصف أزرار مشتركة.',
    'save': 'حفظ',
    'selected': 'محدد',
    'selected_sub': 'تعبئة primaryContainer',
    'disabled': 'معطّل',
    'disabled_sub': 'لا يقبل النقر',
    'destructive': 'خطر',
    'destructive_sub': 'colorScheme.error',
    'dialog_body': 'showSafaehDialog',
    'groups': 'المجموعات',
    'settings': 'الإعدادات',
    'expand': 'توسيع',
    'collapse': 'طي',
    'toggle_rail': 'بدّل سهم السكة',
    'home': 'الرئيسية',
    'selected_index': 'المحدد',
    'on_this_page': 'في هذه الصفحة',
    'alpha': 'ألفا',
    'beta': 'بيتا',
    'gamma': 'غاما',
    'aside': 'جانب',
    'band_copy':
        'SafaehContentBand يوسّط عموداً بحد أقصى من القيود الواردة. الجانب يُخفى على الشاشات الضيقة.',
    'aside_copy': 'إزاحات SafaehEndAsideLayout اليدوية.',
    'aligned_title': 'عنوان محاذى',
    'add': 'إضافة',
    'mock_preview': 'معاينة وهمية',
    'scan_invite': 'امسح الدعوة',
    'point_at_code': 'وجّه نحو الرمز',
    'need_camera': 'يلزم إذن الكاميرا',
    'open_settings': 'افتح الإعدادات',
  },
};

class CatalogItem {
  const CatalogItem({
    required this.id,
    required this.titleKey,
    this.subtitleKey,
  });

  final String id;
  final String titleKey;
  final String? subtitleKey;
}

const catalogItems = <CatalogItem>[
  CatalogItem(id: 'sheet', titleKey: 'sheet', subtitleKey: 'sheet_sub'),
  CatalogItem(id: 'picker', titleKey: 'picker', subtitleKey: 'picker_sub'),
  CatalogItem(
    id: 'tile_picker',
    titleKey: 'tile_picker',
    subtitleKey: 'tile_picker_sub',
  ),
  CatalogItem(id: 'confirm', titleKey: 'confirm', subtitleKey: 'confirm_sub'),
  CatalogItem(
    id: 'text_input',
    titleKey: 'text_input',
    subtitleKey: 'text_input_sub',
  ),
  CatalogItem(
    id: 'sheet_shell',
    titleKey: 'sheet_shell',
    subtitleKey: 'sheet_shell_sub',
  ),
  CatalogItem(
    id: 'sheet_morph',
    titleKey: 'sheet_morph',
    subtitleKey: 'sheet_morph_sub',
  ),
  CatalogItem(
    id: 'option_tiles',
    titleKey: 'option_tiles',
    subtitleKey: 'option_tiles_sub',
  ),
  CatalogItem(id: 'dialog', titleKey: 'dialog', subtitleKey: 'dialog_sub'),
  CatalogItem(id: 'sidenav', titleKey: 'sidenav', subtitleKey: 'sidenav_sub'),
  CatalogItem(
    id: 'sidenav_drawer',
    titleKey: 'sidenav_drawer',
    subtitleKey: 'sidenav_drawer_sub',
  ),
  CatalogItem(
    id: 'floating_nav',
    titleKey: 'floating_nav',
    subtitleKey: 'floating_nav_sub',
  ),
  CatalogItem(
    id: 'page_index',
    titleKey: 'page_index',
    subtitleKey: 'page_index_sub',
  ),
  CatalogItem(
    id: 'page_index_overlay',
    titleKey: 'page_index_overlay',
    subtitleKey: 'page_index_overlay_sub',
  ),
  CatalogItem(
    id: 'content_band',
    titleKey: 'content_band',
    subtitleKey: 'content_band_sub',
  ),
  CatalogItem(
    id: 'end_aside',
    titleKey: 'end_aside',
    subtitleKey: 'end_aside_sub',
  ),
  CatalogItem(
    id: 'aligned_chrome',
    titleKey: 'aligned_chrome',
    subtitleKey: 'aligned_chrome_sub',
  ),
  CatalogItem(id: 'camera', titleKey: 'camera', subtitleKey: 'camera_sub'),
  CatalogItem(
    id: 'qr_overlay',
    titleKey: 'qr_overlay',
    subtitleKey: 'qr_overlay_sub',
  ),
  CatalogItem(
    id: 'qr_message',
    titleKey: 'qr_message',
    subtitleKey: 'qr_message_sub',
  ),
];

String translateCatalog(String key, String locale) {
  return catalogTranslations[locale]?[key] ??
      catalogTranslations['en']?[key] ??
      key;
}
